version: "3.9"
services:
  os:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debian
    ports: 
      - "22:22"
      - "80:80"
    volumes:
      - ./debian/:/home/debian/